### ISSUE TITLE
Can't be installed on vanilla Home Asisstant

### ISSUE THREAD

**Issue by Infinitte** [marcelveldt/hass_emulated_hue#15]
Plugin can't be installed on non hass.io home assistant. Not even using HACS. Manual installation steps or HACS compatible repository will be wonderfull.

Great job, by the way.

**Comment by marcelveldt** [comment]
This is not a COMPONENT/INTEGRATION for home assistant but an ADDON.

**Comment by Infinitte** [comment]
I mean a way to install it on HA running on Ubuntu, with docker for instance. Manual steps to install will be wonderful.

**Comment by MrLemur** [comment]
Can this be run as a separate Docker instance alongside HA?

**Comment by member68** [comment]
Any update on this? Running this project as a docker container would be awesome.

**Comment by marcelveldt** [comment]
expect some updates later this week, including a docker image

**Comment by zewelor** [comment]
I've managed to get it running on docker, without hassio. From docker-compose:

```
  emulated_hue:
    image: marcelveldt/hass-emulated-hue
    container_name: hass-emulated-hue
    restart: "no"
    environment:
      - DATA_DIR=/data
      - HASS_URL=http://homeassistant:8123
      - HASS_TOKEN=token
    volumes:
      - ${DOCKER_DATA_DIR}/emulated_hue:/data
      - ```

**Comment by marcelveldt** [comment]
As @zewelor already discovered we now have a dedicated docker image available on dockerhub: marcelveldt/hass-emulated-hue. You can use that if you want to run the emulator in docker yourself.
