### ISSUE TITLE
Install takes forever on HASS virtual machine

### ISSUE THREAD

**Issue by mnowok** [marcelveldt/hass_emulated_hue#16]
I tried to install the addon on official HASS virtual machine which runs on QNAP.
It starts installing but no error, no result after:

20-09-21 21:15:49 INFO (SyncWorker_5) [supervisor.docker.addon] Start build 62c7908d/amd64-addon-emulated_hue:0.0.4

It never finishes. Any idea?

**Comment by marcelveldt** [comment]
The addon is not prebuilt so will be building from scratch on your setup, this will take a long time.

**Comment by mnowok** [comment]
I know, but 15 minutes? Have it been tested on HASS VM? Is there any setup log I can check for possible build errors?

**Comment by mnowok** [comment]
I've waited a dozen of minutes and the log says:

20-09-29 17:36:30 ERROR (SyncWorker_1) [supervisor.docker.addon] Can't build 62c7908d/amd64-addon-emulated_hue:0.0.4: The command '/bin/sh -c apk add --no-cache --virtual .build-dependencies         build-base         cmake         libuv-dev         libffi-dev         python3-dev         openssl-dev         git     && apk add --no-cache         python3         openssl         supervisor     && mkdir /usr/local/app     && git clone https://github.com/marcelveldt/hass_emulated_hue.git     && pip3 install         --no-cache-dir         -r hass_emulated_hue/requirements.txt     && cp -R hass_emulated_hue/emulated_hue /usr/local/app/     && cp hass_emulated_hue/run.py /usr/local/app/run.py     && apk del --no-cache --purge .build-dependencies     && find /usr/local         \( -type d -a -name test -o -name tests -o -name '__pycache__' \)         -o \( -type f -a -name '*.pyc' -o -name '*.pyo' \)         -exec rm -rf '{}' +     && rm -f -r         /root/.cache         /root/.cmake         /tmp/*         hass_emulated_hue' returned a non-zero code: 1
20-09-29 17:36:30 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-1143294' coro=<AddonManager.rebuild() done, defined at /usr/src/supervisor/supervisor/addons/__init__.py:277> exception=AddonsError()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/docker/addon.py", line 411, in _build
    image, log = self.sys_docker.images.build(
  File "/usr/local/lib/python3.8/site-packages/docker/models/images.py", line 287, in build
    raise BuildError(chunk['error'], result_stream)
docker.errors.BuildError: The command '/bin/sh -c apk add --no-cache --virtual .build-dependencies         build-base         cmake         libuv-dev         libffi-dev         python3-dev         openssl-dev         git     && apk add --no-cache         python3         openssl         supervisor     && mkdir /usr/local/app     && git clone https://github.com/marcelveldt/hass_emulated_hue.git     && pip3 install         --no-cache-dir         -r hass_emulated_hue/requirements.txt     && cp -R hass_emulated_hue/emulated_hue /usr/local/app/     && cp hass_emulated_hue/run.py /usr/local/app/run.py     && apk del --no-cache --purge .build-dependencies     && find /usr/local         \( -type d -a -name test -o -name tests -o -name '__pycache__' \)         -o \( -type f -a -name '*.pyc' -o -name '*.pyo' \)         -exec rm -rf '{}' +     && rm -f -r         /root/.cache         /root/.cmake         /tmp/*         hass_emulated_hue' returned a non-zero code: 1
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/addons/__init__.py", line 301, in rebuild
    await addon.instance.install(addon.version)
  File "/usr/src/supervisor/supervisor/utils/__init__.py", line 32, in wrap_api
    return await method(api, *args, **kwargs)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/supervisor/supervisor/docker/addon.py", line 398, in _install
    self._build(tag)
  File "/usr/src/supervisor/supervisor/docker/addon.py", line 422, in _build
    raise DockerError() from err
supervisor.exceptions.DockerError
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/addons/__init__.py", line 303, in rebuild
    raise AddonsError() from err
supervisor.exceptions.AddonsError

**Comment by mnowok** [comment]
Bump: I tried again and after a night or so it started working correctly, so I assume the issue can be closed.
