### ISSUE TITLE
Trying to get app connected fails for "Colors of Hue"

### ISSUE THREAD

**Issue by gotschi** [marcelveldt/hass_emulated_hue#18]
While the official "Hue Sync" app works fine and does a excellent job for me,
I cannot get this app to recognize the hub:

https://macgenius.co/app/Colors-for-Hue/581915465

Cannot see why it fails though - do you have any recommendations?
Edit: despite some reviews on the page saying it doesn't connect, it worked fine with my original hub
Thanks for this great addon!

**Comment by marcelveldt** [comment]
Can you please give the latest version 0.0.6 a try ?
We changed a lot of stuff to get the pairing process more stable.

Re-open this issue if you still run into trouble. Thanks!

**Comment by gotschi** [comment]
Works fine now, thanks :)
