### ISSUE TITLE
Character encoding - ÅÄÖ shown as ���

### ISSUE THREAD

**Issue by twau** [marcelveldt/hass_emulated_hue#19]
Hi

Å, Ä and Ö characters is shown as "�" in the Official Hue app on Android.
Setup is Home Assistant 0.116.2, ConBee II with the official deCONZ addon.

![Screenshot](https://user-images.githubusercontent.com/536952/95663827-9e820400-0b42-11eb-970f-e93afebf980a.jpg)

**Comment by marcelveldt** [comment]
Version 0.0.6 has just been released which should fix the issue. Please test with that and re-open if your issue is not yet fixed.
Thanks @thesymbol
