### ISSUE TITLE
Android official App finds bridge, immediately switches to no new bridge found, iPhone works perfectly

### ISSUE THREAD

**Issue by Dr4g0nraider** [marcelveldt/hass_emulated_hue#20]
Hey, 
so I am using a Raspberry Pi 4 with a Raspbee and Home Assistant 0.116.3 (HassOS 4.13, supervisor 247) and added the Emulated HUE Integration v0.0.4. The Integration seems to start fine, logs show:

> 2020-10-15 16:37:39,614 INFO Set uid to user 0 succeeded
2020-10-15 16:37:39,618 INFO supervisord started with pid 6
2020-10-15 16:37:40,625 INFO spawned: 'hue' with pid 8
2020-10-15 16:37:41,628 INFO success: hue entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-10-15 16:37:41,671 INFO  emulated_hue.config -- Listen IP address not specified, auto-detected address is 192.168.178.36
2020-10-15 16:37:42,870 INFO  emulated_hue.hue_api -- Started HTTP webserver on port 80
2020-10-15 16:37:42,882 INFO  emulated_hue.hue_api -- Started HTTPS webserver on port 443

So I downloaded the official Philips Hue App (Version 3.43.0 from Sep. 17th 2020) from the Google Play Store on my Pixel 2 Xl (running Android 11) and try to connect to the bridge. It searches for bridges after a couple seconds finds a bridge, but immediately turns back to 

![Screenshot_20201015-185327](https://user-images.githubusercontent.com/56189239/96161712-e70d3900-0f17-11eb-95b0-e9adf529950b.png)

> No new Hue Bridge found

![Screenshot_20201015-185302](https://user-images.githubusercontent.com/56189239/96161710-e674a280-0f17-11eb-9240-3bf09f0f8885.png)

The Integration seems to recognize the attempted connection by the app according to the log and the notification

> 2020-10-15 16:52:33,248 INFO  emulated_hue.config -- Link request detected - Use the Homeassistant frontend to confirm this link request.

I can enable Link Mode by clicking on the link in the notification, and the log shows that it should be active

> 2020-10-15 16:58:00,251 INFO  emulated_hue.config -- Link mode is enabled for the next 60 seconds.

However, the hue app keeps showing the same behavior and immerdiattly shows no new bridge found. I've tried the help and manual IP function, but that didn't work either. I also reset the Addon, the Pi/Home Assistant as well as my phone without any change. Any idea what the issue could be?

So then I took my girlfriends iPhone and if found the emulated bridge, let me chose it and link succesfully without any problems.

Any idea what could cause the issue with the Android App? Is the App itself or perhaps Android 11?

Many thanks and best regards

**Comment by marcelveldt** [comment]
Version 0.0.6 has just been released which should fix the issue. Please test with that and re-open if your issue is not yet fixed.
Thanks!
