### ISSUE TITLE
Can't install on HassOS 4.14 RPI3b+ 32 bit

### ISSUE THREAD

**Issue by Mr-Groch** [marcelveldt/hass_emulated_hue#21]
Install will fail every time with completely system hang-up after about 10 minutes after:

`[supervisor.docker.addon] Starting build for 62c7908d/armv7-addon-emulated_hue:0.0.4`

After hard reboot, addon will fail to start:

```
20-10-21 10:24:03 ERROR (SyncWorker_1) [supervisor.docker] Image 62c7908d/armv7-addon-emulated_hue not exists for addon_62c7908d_emulated_hue
20-10-21 10:24:03 WARNING (MainThread) [supervisor.addons] Can't start Add-on 62c7908d_emulated_hue
```

I can press "rebiuild" button on supervisor addon page, after about 20 minutes:

```
20-10-21 10:31:46 ERROR (SyncWorker_1) [supervisor.docker] Image 62c7908d/armv7-addon-emulated_hue not exists for addon_62c7908d_emulated_hue
20-10-21 10:34:29 INFO (SyncWorker_2) [supervisor.docker.interface] Removeing image 62c7908d/armv7-addon-emulated_hue with latest and None
20-10-21 10:34:29 INFO (SyncWorker_6) [supervisor.docker.addon] Starting build for 62c7908d/armv7-addon-emulated_hue:0.0.4
20-10-21 11:06:25 ERROR (SyncWorker_6) [supervisor.docker.addon] Can't build 62c7908d/armv7-addon-emulated_hue:0.0.4: The command '/bin/sh -c apk add --no-cache --virtual .build-dependencies         build-base         cmake         libuv-dev         libffi-dev         python3-dev         openssl-dev         git     && apk add --no-cache         python3         openssl         supervisor     && mkdir /usr/local/app     && git clone https://github.com/marcelveldt/hass_emulated_hue.git     && pip3 install         --no-cache-dir         -r hass_emulated_hue/requirements.txt     && cp -R hass_emulated_hue/emulated_hue /usr/local/app/     && cp hass_emulated_hue/run.py /usr/local/app/run.py     && apk del --no-cache --purge .build-dependencies     && find /usr/local         \( -type d -a -name test -o -name tests -o -name '__pycache__' \)         -o \( -type f -a -name '*.pyc' -o -name '*.pyo' \)         -exec rm -rf '{}' +     && rm -f -r         /root/.cache         /root/.cmake         /tmp/*         hass_emulated_hue' returned a non-zero code: 1
20-10-21 11:06:25 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-1517' coro=<AddonManager.rebuild() done, defined at /usr/src/supervisor/supervisor/addons/__init__.py:279> exception=AddonsError()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/docker/addon.py", line 413, in _build
    image, log = self.sys_docker.images.build(
  File "/usr/local/lib/python3.8/site-packages/docker/models/images.py", line 287, in build
    raise BuildError(chunk['error'], result_stream)
docker.errors.BuildError: The command '/bin/sh -c apk add --no-cache --virtual .build-dependencies         build-base         cmake         libuv-dev         libffi-dev         python3-dev         openssl-dev         git     && apk add --no-cache         python3         openssl         supervisor     && mkdir /usr/local/app     && git clone https://github.com/marcelveldt/hass_emulated_hue.git     && pip3 install         --no-cache-dir         -r hass_emulated_hue/requirements.txt     && cp -R hass_emulated_hue/emulated_hue /usr/local/app/     && cp hass_emulated_hue/run.py /usr/local/app/run.py     && apk del --no-cache --purge .build-dependencies     && find /usr/local         \( -type d -a -name test -o -name tests -o -name '__pycache__' \)         -o \( -type f -a -name '*.pyc' -o -name '*.pyo' \)         -exec rm -rf '{}' +     && rm -f -r         /root/.cache         /root/.cmake         /tmp/*         hass_emulated_hue' returned a non-zero code: 1
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/addons/__init__.py", line 303, in rebuild
    await addon.instance.install(addon.version)
  File "/usr/src/supervisor/supervisor/utils/__init__.py", line 32, in wrap_api
    return await method(api, *args, **kwargs)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/supervisor/supervisor/docker/addon.py", line 400, in _install
    self._build(tag)
  File "/usr/src/supervisor/supervisor/docker/addon.py", line 424, in _build
    raise DockerError() from err
supervisor.exceptions.DockerError
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/addons/__init__.py", line 305, in rebuild
    raise AddonsError() from err
supervisor.exceptions.AddonsError
```

**Comment by PhillyGilly** [comment]
Also can't install on Raspberry Pi 3  running HassOS 4.16.
Install starts and then runs for about 10 mins before crashing HA.
Hard restart produces:
 20-11-18 18:02:30 ERROR (SyncWorker_0) [supervisor.docker] Image 62c7908d/armv7-addon-emulated_hue not exists for addon_62c7908d_emulated_hue
20-11-18 18:02:30 WARNING (MainThread) [supervisor.addons] Can't start Add-on 62c7908d_emulated_hue
@marcelveldt let me know if I can help trouble shoot.

**Comment by marcelveldt** [comment]
For now, the only thing to do is wait as I have to rewrite a part of the code and the docker deployment.
Currently finishing another big project and once that's done, I'll look into the Emulated Hue again.
So please be patient and I'll give an update when things are ready to test.

**Comment by MaxBec** [comment]
Any progress? I have the same moment. Complete hassio crash after i tried to install the hue emulator.

**Comment by MaxBec** [comment]
Hey guys,

maybe for some of you DiyHue will be a good alternative. Basically for me it was as it combines most hue devices and bridges into one single app. Even routines and hue entertainment is working.

For the easy use I wrote a Hassio addon. You can get it here:

https://github.com/MaxBec/diyHue-hassio

**Comment by marcelveldt** [comment]
The intention of this addon is different than diyHue: bridge Home Assistant devices to a virtual Hue bridge where diyHue is a virtual bridge/hub on it's own. 

My personal situation is that I like Home Assistant to be the hub/bridge for all IoT devices and have the Hue apps still working for things like Entertainment mode. Of course these requirements are personal so diyHue might be a very good fit for others. It's really feature complete while my work here is only covering the basic stuff and in early stage.

FYI: I've rebooted my work on this addon tody so expect some updates to happen this week.

**Comment by alexyao2015** [comment]
This project looks great and looks to have pretty high quality code! I would be curious if the native API ESPHome provides has any sort of rate limits that would hinder its usage for entertainment mode without the throttling that you've implemented.

**Comment by marcelveldt** [comment]
@alexyao2015 thanks!

The throttling should be abandoned or at least configurable per-light.
While I was testing with some lights connected to ZHA, the network got flooded by the entertainment messages (50 messages per-second) so I've put in some very basic throtttling.

I was testing with some ESPHome lights yesterday and they do not suffer of this same implementation so there's some hope. Alternative would be to implement UDP streaming to some popular platforms.
This is also true for the ZHA implementation in HomeAssistant, there's a good chance that the entertainment protocol (message for multiple lights packed into one message) can be implemented there, I already talked about that with the ZHA devs.

**Comment by Sapd** [comment]
I second @alexyao2015 thoughts. The code in DiyHue is quite blown and chaotic. This looks like a good alternative (even when not in a general settings, but restricted to HassIo).

**Comment by alexyao2015** [comment]
I've been a maintainer of diyhue for quite some time now and lately have been working on a refactor for it for the greater part of a year, only to have it kicked to the side. Looking around, it appears that this project does everything that I could have needed from diyhue. 

With regards to UDP streaming, I've previously implemented UDP streaming for ESPHome as a custom component. I wonder if that would be possible to port here. Not too familiar with how this communicates with HA.

Does this properly support the hue api? I know with diyhue, there are quite a few inconsistencies with it that cause certain apps to not function. Are there any known bugs/issues? I'll have to give this a try myself!

Ps. Maybe look at creating an external chat platform or enabling GitHub's own discussions.

**Comment by marcelveldt** [comment]
When I started working on this I created it as a drop-in replacement for the native emulated_hue component in Home Assistant, however that got me in trouble because of the need to bind to port 80 and 443 and the entertainment mode magic.  So I've converted it to be loosely coupled to Home Assistant over websockets which is also very low latency. I discussed this briefly with @balloob, the founder of Home Assistant and the idea is to bring it as an opt-in addon for Home Assistant for users that want the emulated Hue experience (including entertainment mode). At some point it might even replace the current built-in feature maybe. He also brought me in contact with the main dev of the ZHA component to explore if we can get the entertainment mode working with the ZHA implementation of Zigbee in Home Assistant (which would be super cool).

In the meanwhile I must say that this project got a bit lost in the freezer as I was helping out with the new Z-Wave implementation in HASS and switching jobs, Corona stuff etc.

But considered the interest in this project I'll pick it up again and great if I can get some help!
I'm sure with combined forces we can get this project flying at no-time.

BTW: I'm on discord, username marcelveldt

**Comment by Creativesur** [comment]
I don't have idea how to help you but this project is awesome! I need it an i can grateful you if you can make it work again! THANKS!

**Comment by alexyao2015** [comment]
@marcelveldt
Hey again! Been a while as I've been busy with some other projects. Will definitely start to take a look at this project and see how it all works.

**Comment by marcelveldt** [comment]
Version 0.0.6 has just been released which should fix the issue. It should now install fine on (almost) all hardware.

Please test with that and re-open if your issue is not yet fixed.
Thanks!
