### ISSUE TITLE
Choppy Ambilight Transissions with Yeelight

### ISSUE THREAD

**Issue by GaoMax** [marcelveldt/hass_emulated_hue#22]
Hi, 
I‘m having some smoothness issues with Emulated Hue and Ambilight with my Yeelight bulbs. I‘ve enabled music mode on the bulbs and changed transition times (0ms-1000ms in 100ms steps). Any ideas what I can try?

**Comment by marcelveldt** [comment]
Version 0.0.6 has just been released which should fix the issue. Please test with that and re-open if your issue is not yet fixed.
Thanks!
