### ISSUE TITLE
Unable to pair with iPhone

### ISSUE THREAD

**Issue by timknowlden** [marcelveldt/hass_emulated_hue#23]
Hub shows in hue app and notification appears in HA but when enable link mode it doesn’t pair and then the hub is no longer found on searches after that.

**Comment by paviro** [comment]
Seems to work now with the latest update!

**Comment by timknowlden** [comment]
Doesn’t work for me with the latest update, bridge appears in hue app but will not pair. 

I think it might be due to running nginx though as I think this requires port 443

**Comment by marcelveldt** [comment]
the latest version should work better with connecting/pairing the app to the virtual bridge.

@timknowlden be aware that the virtual bridge really needs a dedicated port 80 and 443 to work.
