### ISSUE TITLE
Entities and rooms with umlauts not working hue app

### ISSUE THREAD

**Issue by paviro** [marcelveldt/hass_emulated_hue#30]
My kitchen room and entities have an `ü` in their name (Küche). It seems like the Hue app together with the emulated bridge can't deal with that for some reason (when I used the original Hub umlauts worked). The room containing the `ü` is shown as others, the light insight has no name. When toggling it the light gets turned on in Hass but the hue app crashes. 
![IMG_4746](https://user-images.githubusercontent.com/992826/103143756-152fa600-471d-11eb-9271-7f58af280fdd.jpeg)
![IMG_4747](https://user-images.githubusercontent.com/992826/103143757-182a9680-471d-11eb-8a61-522a200d8693.jpeg)

In sleep cycle the lights are shown correctly so I am not sure if this is anything that can be fixed on your side.
![IMG_4748](https://user-images.githubusercontent.com/992826/103143759-1b258700-471d-11eb-9e57-fe7cdd5798e7.png)

**Comment by paviro** [comment]
Kind of duplicate of #19 sorry about that!

**Comment by xcorp** [comment]
@thesymbol, does this also work in HueEssentials, where the umlauts work fine without your fix.
Will you open a pull request for this fix?

**Comment by thesymbol** [comment]
> @thesymbol, does this also work in HueEssentials, where the umlauts work fine without your fix.
> Will you open a pull request for this fix?
> 
> Update, never mind my first question, check out your branch and can confirm it works fine i both the official Hue app and in HueEssentials.

Might have to create a clean branch and cherry pick out the change as i have done way more changes than just fixing this bug.

**Comment by marcelveldt** [comment]
Version 0.0.6 has just been released which should fix the issue. Please test with that and re-open if your issue is not yet fixed.
Thanks @thesymbol for providing the fix!
