### ISSUE TITLE
'all 4 hue' app will not connect to emulated bridge

### ISSUE THREAD

**Issue by stanwebber** [marcelveldt/hass_emulated_hue#31]
getting most philips apps to pair with the emulated bridge requires a little bit of finesse, but they will eventually connect.  i must have tried over 40 times with the 'all 4 hue' app on multiple android devices in every automatic iteration or manual sequence i could think of with no luck.  it's the only app that absolutely refuses to recognize there's a hub at the specified ip address.  the emulated bridge doesn't even flash a notification in lovelace to indicate that anything connected.  i've even tried initiating a connection with a different app (on the same phone) to get the notification, killing said app, pressing the simulated button before and after switching over to 'all 4 hue' to start the automatic and manual discovery processes.  the app has no problems connecting to a physical philips v2 bridge on the same or an alternate network.

**Comment by marcelveldt** [comment]
Version 0.0.6 has just been released which should fix the issue. Please test with that and re-open if your issue is not yet fixed.
