### ISSUE TITLE
Invalid request

### ISSUE THREAD

**Issue by zewelor** [marcelveldt/hass_emulated_hue#32]
Hi

thanks for great addon ! I'm testing it with few light, and found some WARNING in logs, lights seems to work fine except of that. 
```WARNING emulated_hue.api -- Invalid request: <Request POST /api/ba5bca5d868e448f8e74/groups/ > --> {'lights': ['6', '7', '9', '32'], 'type': 'LightGroup'}```

Im testing with Philiph tv PUS8535.

**Comment by marcelveldt** [comment]
Version 0.0.6 has just been released which should fix the issue. Please test with that and re-open if your issue is not yet fixed.

**Comment by zewelor** [comment]
Updated to newest docker and still has same problem:

```2020-12-31 11:31:08,972 WARNING emulated_hue.api -- Invalid/unknown request: <Request POST /api/ba5bca5d868e448f8e74/groups/ > --> {'lights': ['6', '8', '9', '32'], 'type': '
LightGroup'```

**Comment by marcelveldt** [comment]
Sorry, I now spot the trailing slash. I fixed that yesterday but did not yet get included in the build.
I'll provide a new build later today

**Comment by zewelor** [comment]
Can confirm its solved now, thanks !
