### ISSUE TITLE
Official Hue app asking for update

### ISSUE THREAD

**Issue by Kvanr23** [marcelveldt/hass_emulated_hue#33]
Hello, I installed the new version 0.0.5, on my HassOS 5.9 with Home assistant version 2020.12.1.
Everything goes smooth as butter until after I connected with it with the 'link button'.
The app tells me there is an update available. 

I tried rebooting and reinstalling the addon but to no avail.

**Comment by stanwebber** [comment]
I am running the exact same versions for those 3 components and do not get an update prompt with the current philips app on android oreo or pie.

**Comment by Kvanr23** [comment]
I am running on android 10, but I will try my old phone with (if I remember correctly) Oreo.

**Comment by xcorp** [comment]
@Kvanr23 if you click the little info button in the hue app for the bridge and check what SW: is reporting, it should be 1940042020

**Comment by xcorp** [comment]
Philips has bumped their version, see https://github.com/marcelveldt/hass_emulated_hue/pull/34 for fix

**Comment by marcelveldt** [comment]
Version 0.0.6 has just been released which should fix the issue. Please test with that and re-open if your issue is not yet fixed.
Thanks @xcorp for the version bump notice!
