### ISSUE TITLE
can't connect Hue Essentials app

### ISSUE THREAD

**Issue by iroQuai** [marcelveldt/hass_emulated_hue#35]
first of all: thanks for this amazing program! this could really fill the last gap now I've switched from Hue gateway to Home Assistant. 

I am able to connect via the official Hue app (although I get that update error someone else made an issue about already)

Too bad I cannot connect with the hue essentials app! I get errors both automatically (left) as manually (right)
https://imgur.com/kI5mvZ3

any tip?

**Comment by stanwebber** [comment]
i got it to connect to hue essentials despite the error.  press the emulated button first, then do a manual bridge search by ip address within 30sec.

**Comment by iroQuai** [comment]
I have no idea how to press the emulated button without trying to connect to the bridge with an app (more specific: the official hue app.)

**Comment by alexyao2015** [comment]
Yes, this appears to be a bug. I was able to get it connected by pairing then backing out and reentering.

**Comment by marcelveldt** [comment]
Version 0.0.6 has just been released which should fix the issue. Please test with that and re-open if your issue is not yet fixed.
