### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by WolfsWelpe** [marcelveldt/hass_emulated_hue#38]
Hello,
Im not able to install the addon. I followed the instructions but Im getting this error everytime:
![image](https://user-images.githubusercontent.com/17033125/103381172-4af0d800-4aeb-11eb-84da-61ddefbb1511.png)

**Comment by marcelveldt** [comment]
The image is still building to docker hub. Please try again in an hour or so.

**Comment by WolfsWelpe** [comment]
Ohh ok :D Sorry ^^
