### ISSUE TITLE
Philips TV not discovering emulated hue

### ISSUE THREAD

**Issue by Mr-Groch** [marcelveldt/hass_emulated_hue#41]
Hi, I have non Android Philips TV that doesn't discover emulated hue bridge for use with Ambilight+Hue.

I have also diyHue setup and diyHue bridge is working with my TV. I think that problem is with SSDP discovery.

This is ssdp from emulated hue:

```
[+] ('192.168.1.211', 57234)
HTTP/1.1 200 OK
CACHE-CONTROL: max-age=60
EXT:
LOCATION: http://192.168.1.211:80/description.xml
SERVER: FreeRTOS/6.0.5, UPnP/1.0, IpBridge/0.1
hue-bridgeid: 1234
ST: urn:schemas-upnp-org:device:basic:1
USN: uuid:Socket-1_0-221438K0100073::urn:schemas-upnp-org:device:basic:1
```

And this from diyHue:

```
[+] ('192.168.1.211', 1900)
HTTP/1.1 200 OK
HOST: 239.255.255.250:1900
EXT:
CACHE-CONTROL: max-age=100
LOCATION: http://192.168.1.211:80/description.xml
SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.20.0
hue-bridgeid: B827EBFFFEB31E9E
ST: upnp:rootdevice
USN: uuid:2f402f80-da50-11e1-9b23-b827ebb31e9e::upnp:rootdevice


[+] ('192.168.1.211', 1900)
HTTP/1.1 200 OK
HOST: 239.255.255.250:1900
EXT:
CACHE-CONTROL: max-age=100
LOCATION: http://192.168.1.211:80/description.xml
SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.20.0
hue-bridgeid: B827EBFFFEB31E9E
ST: uuid:2f402f80-da50-11e1-9b23-b827ebb31e9e
USN: uuid:2f402f80-da50-11e1-9b23-b827ebb31e9e


[+] ('192.168.1.211', 1900)
HTTP/1.1 200 OK
HOST: 239.255.255.250:1900
EXT:
CACHE-CONTROL: max-age=100
LOCATION: http://192.168.1.211:80/description.xml
SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.20.0
hue-bridgeid: B827EBFFFEB31E9E
ST: urn:schemas-upnp-org:device:basic:1
USN: uuid:2f402f80-da50-11e1-9b23-b827ebb31e9e
```

I'm using both on the same host (ofcourse not simultaneously), so the IP is the same...

description.xml looks almost the same - differnece that UDN match ssdp USN in diyHue, this is from Emulated Hue:

```
<root xmlns="urn:schemas-upnp-org:device-1-0">
<specVersion>
<major>1</major>
<minor>0</minor>
</specVersion>
<URLBase>http://192.168.1.211:80/</URLBase>
<device>
<deviceType>urn:schemas-upnp-org:device:Basic:1</deviceType>
<friendlyName>Home Assistant</friendlyName>
<manufacturer>Signify</manufacturer>
<manufacturerURL>http://www.philips.com</manufacturerURL>
<modelDescription>Philips hue Personal Wireless Lighting</modelDescription>
<modelName>Philips hue bridge 2015</modelName>
<modelNumber>BSB002</modelNumber>
<modelURL>http://www.meethue.com</modelURL>
<serialNumber>B682D3FFFE45AC29</serialNumber>
<UDN>uuid:2f402f80-da50-11e1-9b23-b682d345ac29</UDN>
<presentationURL>index.html</presentationURL>
<iconList>
<icon>
<mimetype>image/png</mimetype>
<height>48</height>
<width>48</width>
<depth>24</depth>
<url>hue_logo_0.png</url>
</icon>
<icon>
<mimetype>image/png</mimetype>
<height>120</height>
<width>120</width>
<depth>24</depth>
<url>hue_logo_3.png</url>
</icon>
</iconList>
</device>
</root>
```

and this from diyHue:

```
<root xmlns="urn:schemas-upnp-org:device-1-0">
<specVersion>
<major>1</major>
<minor>0</minor>
</specVersion>
<URLBase>http://192.168.1.211:80/</URLBase>
<device>
<deviceType>urn:schemas-upnp-org:device:Basic:1</deviceType>
<friendlyName>Philips hue (192.168.1.211)</friendlyName>
<manufacturer>Signify</manufacturer>
<manufacturerURL>http://www.philips.com</manufacturerURL>
<modelDescription>Philips hue Personal Wireless Lighting</modelDescription>
<modelName>Philips hue bridge 2015</modelName>
<modelNumber>BSB002</modelNumber>
<modelURL>http://www.meethue.com</modelURL>
<serialNumber>b827ebb31e9e</serialNumber>
<UDN>uuid:2f402f80-da50-11e1-9b23-b827ebb31e9e</UDN>
<presentationURL>index.html</presentationURL>
<iconList>
<icon>
<mimetype>image/png</mimetype>
<height>48</height>
<width>48</width>
<depth>24</depth>
<url>hue_logo_0.png</url>
</icon>
</iconList>
</device>
</root>
```

I'm using diyHue currently but prefer Emulated Hue because of better HA integration.

**Comment by marcelveldt** [comment]
Thanks for the detailed report. We'll adjust the discovery schemes according to your info so we can see if that helps.
I'll let you know once a new version is available.

**Comment by Mr-Groch** [comment]
Problem can be also bad MAC adress used as serialNumber in Emulated Hue. MAC address for external network interface is b8:27:eb:b3:1e:9e - diyHue uses it OK in SerialNumber, UDN and hue-bridgeid fields (ssdp, and description.xml) but I can configure it in env variables - Emulated Hue cannot be configured (only autodiscovery that discovers bad, internal virtaul, MAC address I think)

**Comment by Mr-Groch** [comment]
Yes, MAC is definitely one of the problems:

```
2020-12-31 18:56:36,504 INFO  emulated_hue.config -- Auto detected listen IP address is 192.168.1.211
2020-12-31 18:56:36,586 DEBUG getmac -- Raw MAC found: None
```

**Comment by marcelveldt** [comment]
It falls back to some default/hardcoded mac when it can't be autodetected which worked correctly before on my Philips TV. Although we should probably find a way to properly determine the mac on docker this shouldn't be the issue of the failing discovery. @alexyao2015 fixed some stuff yesterday that might solve the discovery issue but we're still doing some tests.

For now I'll build a new 0.0.8 version so you can test with yesterday's changes to see if it helps.

**Comment by marcelveldt** [comment]
version 0.0.8 is currently building to docker hub and should be available within an hour.
can you give that a test drive please ?

**Comment by Mr-Groch** [comment]
Sorry, discovery still fails and still ssdp message looks like before:

```
[+] ('192.168.1.211', 52385)
HTTP/1.1 200 OK
CACHE-CONTROL: max-age=60
EXT:
LOCATION: http://192.168.1.211:80/description.xml
SERVER: FreeRTOS/6.0.5, UPnP/1.0, IpBridge/0.1
hue-bridgeid: 1234
ST: urn:schemas-upnp-org:device:basic:1
USN: uuid:Socket-1_0-221438K0100073::urn:schemas-upnp-org:device:basic:1
```

```
<root xmlns="urn:schemas-upnp-org:device-1-0">
<specVersion>
<major>1</major>
<minor>0</minor>
</specVersion>
<URLBase>http://192.168.1.211:80/</URLBase>
<device>
<deviceType>urn:schemas-upnp-org:device:Basic:1</deviceType>
<friendlyName>Home Assistant</friendlyName>
<manufacturer>Signify</manufacturer>
<manufacturerURL>http://www.philips-hue.com</manufacturerURL>
<modelDescription>Philips hue Personal Wireless Lighting</modelDescription>
<modelName>Philips hue bridge 2015</modelName>
<modelNumber>BSB002</modelNumber>
<modelURL>http://www.philips-hue.com</modelURL>
<serialNumber>b827ebb31e9e</serialNumber>
<UDN>uuid:2f402f80-da50-11e1-9b23-b827ebb31e9e</UDN>
<presentationURL>index.html</presentationURL>
<iconList>
<icon>
<mimetype>image/png</mimetype>
<height>48</height>
<width>48</width>
<depth>24</depth>
<url>hue_logo_0.png</url>
</icon>
</iconList>
</device>
</root>
```

MAC is correctly detected now  and brisge serial id changed, so I have been forced to wipe old config and cert to get it back to work with Hue Android App, but no luck with Philips TV...

As you can see, difference from diyHue in ssdp is:
- 1 ssdp message instead of 3
- hue-bridgeid is 1234 instead of bridge serial
- USN does not match <UDN> field in description.xml
- bridge serial number is pure MAC address without FFFE in the middle

**Comment by alexyao2015** [comment]
Are you able to confirm that diyhue does connect without issues currently? I know I've seen bug reports specifically relating the the Phillips TV and ambilight+hue in the past from diyhue. 

The bridge serial in the xml should be correct here as purely the Mac address, so that's unlikely to be causing the issue. It seems like it would be more likely that those other variations are causing it.

**Comment by Mr-Groch** [comment]
Yes, I can confirm, that my Philips TV discovers and connects to diyHue without problem (i'm switching back to diyHue after each test, becaouse I'm using ambilight+hue fucntion often ;) )

**Comment by Mr-Groch** [comment]
OK, I made some tests, I have copied 4 lines from diyHue code, and replaced in upnp.py in this repo:

1. Lines 27-42 replaced with:
```
        self.response_message = 'HTTP/1.1 200 OK\r\nHOST: 239.255.255.250:1900\r\nEXT:\r\nCACHE-CONTROL: max-age=100\r\nLOCATION: http://' + config.ip_addr + ':' + str(config.http_port) + '/description.xml\r\nSERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.20.0\r\nhue-bridgeid: ' + config.bridge_id + '\r\n'
        self.custom_response_message = {0: {"st": "upnp:rootdevice", "usn": "uuid:" + config.bridge_uid + "::upnp:rootdevice"}, 1: {"st": "uuid:" + config.bridge_uid, "usn": "uuid:" + config.bridge_uid}, 2: {"st": "urn:schemas-upnp-org:device:basic:1", "usn": "uuid:" + config.bridge_uid}}
```
2. Line 95 relaced with:
```
                for x in range(3):
                    resp_socket.sendto(bytes(self.response_message + "ST: " + self.custom_response_message[x]["st"] + "\r\nUSN: " + self.custom_response_message[x]["usn"] + "\r\n\r\n", "utf8"), addr)
```

And my Philips TV detects Emulated Hue now ;)

**Comment by marcelveldt** [comment]
Great! I was about to make the same changes. Maybe the second change is not even needed btw.
One single message with correct bridge id and USN should suffice is my guess

**Comment by Mr-Groch** [comment]
I have tried at first just single message like this:

```
        resp_template = """HTTP/1.1 200 OK
CACHE-CONTROL: max-age=60
EXT:
LOCATION: http://{0}:{1}/description.xml
SERVER: FreeRTOS/6.0.5, UPnP/1.0, IpBridge/0.1
hue-bridgeid: {2}
ST: urn:schemas-upnp-org:device:basic:1
USN: uuid:{3}::urn:schemas-upnp-org:device:basic:1

"""

        self.upnp_response = (
            resp_template.format(config.ip_addr, config.http_port, config.bridge_id, config.bridge_uid)
            .replace("\n", "\r\n")
            .encode("utf-8")
        )
```

But that didn't help... Only after applying all 3 messages it detected emulated hue bridge

**Comment by marcelveldt** [comment]
can you test with this message:

`        resp_template = """HTTP/1.1 200 OK
CACHE-CONTROL: max-age=60
EXT:
LOCATION: http://{0}:{1}/description.xml
SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.20.0
hue-bridgeid: {2}
ST: uuid:{3}
USN: uuid:{3}

"""

        self.upnp_response = (
            resp_template.format(config.ip_addr, config.http_port, config.bridge_id, config.bridge_uid)
            .replace("\n", "\r\n")
            .encode("utf-8")
        )
`

**Comment by Mr-Groch** [comment]
Yes, you're right - I've tried also yours modifier response with just one message and that also worked 👍

**Comment by marcelveldt** [comment]
great, just as I thought. Thanks for your help testing!!!

**Comment by marcelveldt** [comment]
Are you able to test one more thing in a few minutes once I fixed the code ?

**Comment by Mr-Groch** [comment]
Yes, I can test, but currently I have not menaged to connect to HA with my local repo yet

**Comment by marcelveldt** [comment]
version 0.0.9 is now up. it includes the SSDP broadcast fix. Can you let me know if is indeed fixed now ?

**Comment by Mr-Groch** [comment]
Thanks, I can confirm it is fixed now! Successfully discovered and linked Emulated Hue with Ambilight+Hue on my Philips TV
