### ISSUE TITLE
Unable to limit entries

### ISSUE THREAD

**Issue by MrGravgaard** [marcelveldt/hass_emulated_hue#5]
i*m trying to limit the entries that emualted_hue registeres as I have a LOT of IHC entries. 

No matter what I do, the configuration is not registered from configuration.yaml or the config setting in the add-in. I've tried to set expose_by_default: false but this does not help. I've tried to set all light entries to hidden - this does not help. 

![Udklip](https://user-images.githubusercontent.com/16425360/76169705-379b0780-617b-11ea-863d-51be76c2569f.JPG)

I the analyzed your code and it seems that you are taking the configuration from emulated_hue.json. Where is this file located? It is not in the config directory.  

![Udklip2](https://user-images.githubusercontent.com/16425360/76169743-92346380-617b-11ea-9a72-08705d40f88d.JPG)

It seems like it ignores all configuration.

**Comment by Destarianon** [comment]
Does anyone have an update for this? I have been trying for 2 straight days to get the addon to use a configuration. It ignores everything and always starts up with the defaults.

**Comment by marcelveldt** [comment]
This addon is still very much in alpha/experimental stage. These configuration options are not even supported yet.
It will take me some time to make it more mature.

**Comment by marcelveldt** [comment]
The latest version has support for deleting lights and groups that were auto added by HA.
Just use the Hue app for that and they will stay away until you do a manual scan or reset.
