### ISSUE TITLE
Cannot create Entertainment Area in Hue App

### ISSUE THREAD

**Issue by Hukuma1** [marcelveldt/hass_emulated_hue#6]
Unable to create an Entertainment Area in the Hue iOS App (which is required to be able to add Hue lights to Razer Chroma) because it shows that the lights need a firmware update. Obviously cannot update the light firmware since they're not Philips Hue lights. Using Yeelight lights if it matters.

Also does not work with official Hue Sync app on PC.

![hue-4](https://user-images.githubusercontent.com/54511555/76688291-c29b5800-65e8-11ea-9e13-be0aa070ecc8.png)

**Comment by Hukuma1** [comment]
Adding photos for reference. I wonder if this is blocked until the light bulb firmware will be showing latest version? (like the bridge)

![hue1](https://user-images.githubusercontent.com/54511555/76688222-21140680-65e8-11ea-81e8-e55fd635d6fd.PNG)

![hue2](https://user-images.githubusercontent.com/54511555/76688224-25402400-65e8-11ea-981c-9d76e7d5469c.PNG)

![hue3](https://user-images.githubusercontent.com/54511555/76688225-283b1480-65e8-11ea-8638-fcab3bd7be74.PNG)

![hue4](https://user-images.githubusercontent.com/54511555/76688226-2bce9b80-65e8-11ea-976d-18e9fb2e492e.PNG)

**Comment by Hukuma1** [comment]
Btw the Yeelights provide "richer colors" than the Hue bulb equivalent. So the first screen advising me to use other bulbs is... interesting. In any case, here's a link to the specific model if it helps to debug: https://www.yeelight.com/en_US/product/lemon2-color

**Comment by groft389** [comment]
Hello,

Here the same Problem sadly :( 
Would love to getting this fixed as I only need this Feature D:

**Comment by groft389** [comment]
Is there something new about this ?

**Comment by flyinghuman** [comment]
same here; in the app i cannot create a Entertainment Area (Hue Essentials App, Original Hue cannot even connect to the emulated hue bridge). Any ideas how we can get entertainment to work (i need this also for Razer Chroma). Thanks! log says no errors; only app denys that no compatible hardware was found. I have the LEDVANCE LED Strip connected to original hue bridge (connected to homeassistant).

**Comment by marcelveldt** [comment]
Please have a little bit of patience. This addon is still in early development phase and needs a lof more work and testing. I had no idea it would be so popular. Some parts of the code need to be updated/matured. At this time I'm still working on another big project but once that's finished within a few weeks, I'll start working on this Emulated Hue project again.

**Comment by marcelveldt** [comment]
The latest version has a lot of fixes. Please test with that and report back (re-open this issue) if you still run into trouble. Thanks!

**Comment by AustrianTree** [comment]
I have a "innr" led strip, model FL120 C. I can add it in the hue App, connect it to my hue bridge and everything is fine. But I can't create a Entertainment Area? why is that so?
