### ISSUE TITLE
Ambilight+Hue flashy transitions

### ISSUE THREAD

**Issue by Cludch** [marcelveldt/hass_emulated_hue#7]
Hey,

so I finally managed to migrate my Hue lights to deConz and install your add-on. Connecting it to my Android TV was easy and worked pretty well (yay!).

However, watching TV, I noticed that the colors of the lights simply jump and have no transition, which makes it annoying to use, sadly.

Is it possible to add a transition? I will try to have a look at the source this weekend.

And thanks a lot for your effort!

**Comment by marcelveldt** [comment]
There should be a transition but I did not test with deconz, only with the ZHA integration and some esphome lights.

Maybe deConz does not support a transition ?

**Comment by Cludch** [comment]
Hm, that's weird.

Is there a way to test transitions?
I use the `transition` key with `light.turn_off` and `light.turn_on` and this works.

**Comment by marcelveldt** [comment]
OK, I will take a look later this week.

**Comment by Cludch** [comment]
I did some further testing.
The lights do have some kind of transition and transition itself works through the HA and/or deConz webinterface. So there must be an issue with the algorithm.
Another idea I had, that it might be caused by the slow transition time: https://github.com/marcelveldt/hass_emulated_hue/blob/master/emulated_hue/hue_entertainment.py#L145

Any idea how I could further assist or debug this on my own?

**Comment by Cludch** [comment]
This issue does not happen when using Philips Hue Sync.

**Comment by marcelveldt** [comment]
The latest version has a lot of fixes. Please test with that and report back (re-open this issue) if you still run into trouble. Thanks!
